# Project information
site_name: C.R Docs
site_url: http://clubrescue.github.io/crdocs-nl
site_author: Ruud Borghouts
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project – customizable,
  searchable, mobile-friendly, 40+ languages

# Repository
repo_name: clubrescue/crdocs-nl
repo_url: https://github.com/clubrescue/crdocs-nl
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2017 Ruud Borghouts, CC BY-SA 4.0.

# Configuration
theme:
  name: material
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: nl
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: light blue
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: logo

# Plugins
plugins:
  - search
  #- redirects:
  - minify:
      minify_html: true
  #- mermaid2

extra_javascript:
  - assets/js/mermaid.min.js

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/clubrescue
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ruudborghouts

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: http://clubrescue.github.io
  - IT Suite for NP:
    - Introduction: itsuitefornonprofits/index.md
    - High level view: itsuitefornonprofits/highlevelview.md
    - Components: itsuitefornonprofits/components.md
    - Cost estimate: itsuitefornonprofits/costestimate.md
  - Club.Redders:
    - Tooling: clubrescue/tooling.md
    - Releases: clubrescue/releases.md
    - Generaties: clubrescue/generations.md
    - AVG: clubrescue/privacy.md
  - C.R Installatie:
    - Installatie 1: clubrescue/installation/index.md
    - Installatie 2: clubrescue/installation/installation.md
  - C.R Modules:
    - Mijn C.R:
      - Mijn C.R: clubrescue/modules/mycr.md
      - Mijn C.R-WP: clubrescue/modules/mycr-wp.md
    - Ledenadministratie: clubrescue/modules/membermanagement.md
    - Competenties: clubrescue/modules/diplomamanagement.md
    - Weekroosters: clubrescue/modules/customscheduling.md
    - Maillijsten: clubrescue/modules/mailinglists.md
    - Contributie: clubrescue/modules/contribution.md
    - Boekhouding: clubrescue/modules/accounting.md
    - PDF-merger: clubrescue/modules/pdfmerger.md
    - Data imports: clubrescue/modules/import.md
    - SDEM (modules): clubrescue/modules/sdem.md
    - Beheer: clubrescue/modules/admin.md
  - Collaboration suite:
    - Suites: collaborationsuite/index.md
    - Office 365: collaborationsuite/office365.md
    - End-user instructions:
      - Turning on MFA (O365): collaborationsuite/office365mfa.md
      - Group management (O365): collaborationsuite/office365groupmanagement.md
  - Form editor:
    - Form editors: formeditor/index.md
    - MachForm: formeditor/machform.md
  - Site editor:
    - Site editors: siteeditor/index.md
    - WordPress: siteeditor/wordpress.md
  - About us:
    - About: aboutus/index.md
    - Repositories: https://github.com/clubrescue
    - Vacancies: aboutus/vacancies.md
  #- End-user instructions:
      #- End-user instructions: end-users.md