# Project information
site_name: IT Suite voor non profits | C.R Docs
site_url: http://clubrescue.github.io/crdocs-nl
site_author: Ruud Borghouts
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project – customizable,
  searchable, mobile-friendly, 40+ languages

# Repository
repo_name: clubrescue/crdocs-nl
repo_url: https://github.com/clubrescue/crdocs-nl
#edit_uri: ""

# Copyright
copyright: Copyright &copy; 2017 Ruud Borghouts, CC BY-SA 4.0.

# Configuration
theme:
  name: material
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: nl
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: light blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Plugins
plugins:
  - search
  #- redirects:
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/clubrescue
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ruudborghouts

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - ITSuite4NP: http://clubrescue.github.io/crdocs
  - Club.Rescue:
    - Releases: index.md
    - Modules: index.md
    - Generaties: index.md
    - Privacy vriendelijk gebruik van Sportlink: index.md
    - Werkinstructie installatie en configuratie: index.md
    - Autorisatie concept: index.md
    - Wijzigingen beheer database: index.md
    - Vacatures core en module developers: index.md