# Project information
site_name: C.R Docs
site_url: http://clubrescue.github.io/crdocs-nl
site_author: Ruud Borghouts
site_description: >-
  Create a branded static site from a set of Markdown files to host the
  documentation of your Open Source or commercial project – customizable,
  searchable, mobile-friendly, 40+ languages

# Repository
repo_name: clubrescue/crdocs-nl
repo_url: https://github.com/clubrescue/crdocs-nl
edit_uri: edit/dev/docs/

# Copyright
copyright: Copyright &copy; 2017 Ruud Borghouts, CC BY-SA 4.0.

# Configuration
theme:
  name: material
  custom_dir: overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: nl
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: light blue
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: logo

# Plugins
plugins:
  - search
  #- redirects:
  - minify:
      minify_html: true
  #- mermaid2

extra_javascript:
  - assets/js/mermaid.min.js

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/clubrescue
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ruudborghouts

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: http://clubrescue.github.io
  - Club.Redders:
    - Tooling: clubrescue/tooling.md
    - Releases: clubrescue/releases.md
    - Generaties: clubrescue/generations.md
    - AVG: clubrescue/privacy.md
  - Installatie:
    - Installatie 1: installation/index.md
    - Installatie 2: installation/installation.md
  - Modules:
    - Mijn C.R:
      - Mijn C.R: modules/mycr.md
      - Mijn C.R-WP: modules/mycr-wp.md
    - Ledenadministratie: modules/membermanagement.md
    - Competenties: modules/diplomamanagement.md
    - Weekroosters: modules/customscheduling.md
    - Maillijsten: modules/mailinglists.md
    - Contributie: modules/contribution.md
    - Boekhouding: modules/accounting.md
    - PDF-merger: modules/pdfmerger.md
    - Data imports: modules/import.md
    - SDEM (modules): modules/sdem.md
    - Beheer: modules/admin.md
  - End-user instructions:
    - End-user instructions: end-users.md
    #Gebruik de FQDN anders blijft het menu ook vanuit modules hier hangen.
    #- Mijn C.R: modules/mycr.md
    #- Weekroosters: modules/customscheduling.md
    #- Competenties: modules/diplomamanagement.md
    #- Aanzetten MFA: https://clubrescue.github.io/collaborationsuite/office365mfa
    #- O365 Groepenbeheer: https://clubrescue.github.io/collaborationsuite/office365groupmanagement